name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install easyocr pylint openai flask flask_cors
        pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121/torch_stable.html
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
